<a href="https://colab.research.google.com/github/T-Naveen-2308/Income-Prediction/blob/main/ML_CBP_Income_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import gdown

In [ ]:
file_id = "1IzivFNReeDrOffY2QZMaQ0X9ineEqTBv"
url = f"https://drive.google.com/uc?id={file_id}"

output = "adult.csv"
gdown.download(url, output, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1IzivFNReeDrOffY2QZMaQ0X9ineEqTBv
To: /content/adult.csv
100%|██████████| 3.33M/3.33M [00:00<00:00, 145MB/s]

'adult.csv'

In [ ]:
data = pd.read_csv(output)
data

,Age,Work Class,Education,Education Number,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,Capital Loss,Hours Per Week,Native Country,Income
0,90,?,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [ ]:
data.replace('?', pd.NA, inplace=True)
data.dropna(inplace=True)
data

,Age,Work Class,Education,Education Number,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,Capital Loss,Hours Per Week,Native Country,Income
1,82,Private,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
3,54,Private,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
5,34,Private,HS-grad,9,Divorced,Other-service,Unmarried,White,Female,0,3770,45,United-States,<=50K
6,38,Private,10th,6,Separated,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [ ]:
data["Income"] = data["Income"].map({"<=50K": 0, ">50K": 1})
data

,Age,Work Class,Education,Education Number,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,Capital Loss,Hours Per Week,Native Country,Income
1,82,Private,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,0
3,54,Private,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,0
4,41,Private,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,0
5,34,Private,HS-grad,9,Divorced,Other-service,Unmarried,White,Female,0,3770,45,United-States,0
6,38,Private,10th,6,Separated,Adm-clerical,Unmarried,White,Male,0,3770,40,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,0
32557,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32558,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32559,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32560,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0

In [ ]:
data["Gender"] =  data["Gender"].map({"Male": 0, "Female": 1})
data

,Age,Work Class,Education,Education Number,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,Capital Loss,Hours Per Week,Native Country,Income
1,82,Private,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,1,0,4356,18,United-States,0
3,54,Private,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,1,0,3900,40,United-States,0
4,41,Private,Some-college,10,Separated,Prof-specialty,Own-child,White,1,0,3900,40,United-States,0
5,34,Private,HS-grad,9,Divorced,Other-service,Unmarried,White,1,0,3770,45,United-States,0
6,38,Private,10th,6,Separated,Adm-clerical,Unmarried,White,0,0,3770,40,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,0,0,0,40,United-States,0
32557,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,1,0,0,38,United-States,0
32558,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,0,0,0,40,United-States,1
32559,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,1,0,0,40,United-States,0
32560,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,0,0,0,20,United-States,0

In [ ]:
data = pd.get_dummies(data, columns=["Work Class", "Education", "Marital Status", "Occupation", "Relationship", "Race", "Native Country"])
data

,Age,Education Number,Gender,Capital Gain,Capital Loss,Hours Per Week,Income,Work Class_Federal-gov,Work Class_Local-gov,Work Class_Private,...,Native Country_Portugal,Native Country_Puerto-Rico,Native Country_Scotland,Native Country_South,Native Country_Taiwan,Native Country_Thailand,Native Country_Trinadad&Tobago,Native Country_United-States,Native Country_Vietnam,Native Country_Yugoslavia
1,82,9,1,0,4356,18,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,54,4,1,0,3900,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,41,10,1,0,3900,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
5,34,9,1,0,3770,45,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
6,38,6,0,0,3770,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,0,0,0,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
32557,27,12,1,0,0,38,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
32558,40,9,0,0,0,40,1,False,False,True,...,False,False,False,False,False,False,False,True,False,False
32559,58,9,1,0,0,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
32560,22,9,0,0,0,20,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
data = data.astype(int)
data

,Age,Education Number,Gender,Capital Gain,Capital Loss,Hours Per Week,Income,Work Class_Federal-gov,Work Class_Local-gov,Work Class_Private,...,Native Country_Portugal,Native Country_Puerto-Rico,Native Country_Scotland,Native Country_South,Native Country_Taiwan,Native Country_Thailand,Native Country_Trinadad&Tobago,Native Country_United-States,Native Country_Vietnam,Native Country_Yugoslavia
1,82,9,1,0,4356,18,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,54,4,1,0,3900,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4,41,10,1,0,3900,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
5,34,9,1,0,3770,45,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
6,38,6,0,0,3770,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,0,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
32557,27,12,1,0,0,38,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
32558,40,9,0,0,0,40,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
32559,58,9,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
32560,22,9,0,0,0,20,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

columns_to_scale = ["Age", "Education Number", "Capital Gain", "Capital Loss", "Hours Per Week"]

scaler = StandardScaler()
data[columns_to_scale] = scaler.fit_transform(data[columns_to_scale])

X = data.drop("Income", axis=1)
y = data["Income"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 87.32
Test Accuracy : 82.75

Confusion Matrix:
 [[6089  665]
 [ 896 1399]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.90      0.89      6754
           1       0.68      0.61      0.64      2295

    accuracy                           0.83      9049
   macro avg       0.77      0.76      0.76      9049
weighted avg       0.82      0.83      0.82      9049

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='gini', random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 97.91
Test Accuracy : 81.82

Confusion Matrix:
 [[6000  754]
 [ 891 1404]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.89      0.88      6754
           1       0.65      0.61      0.63      2295

    accuracy                           0.82      9049
   macro avg       0.76      0.75      0.76      9049
weighted avg       0.81      0.82      0.82      9049

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='entropy', random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 97.91
Test Accuracy : 81.57

Confusion Matrix:
 [[5978  776]
 [ 892 1403]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.89      0.88      6754
           1       0.64      0.61      0.63      2295

    accuracy                           0.82      9049
   macro avg       0.76      0.75      0.75      9049
weighted avg       0.81      0.82      0.81      9049

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='log_loss', random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 97.91
Test Accuracy : 81.57

Confusion Matrix:
 [[5978  776]
 [ 892 1403]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.89      0.88      6754
           1       0.64      0.61      0.63      2295

    accuracy                           0.82      9049
   macro avg       0.76      0.75      0.75      9049
weighted avg       0.81      0.82      0.81      9049

In [ ]:
from sklearn.linear_model import LogisticRegression

log_reg  = LogisticRegression(random_state=42)
log_reg .fit(X_train, y_train)

y_pred = log_reg.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = log_reg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 85.10
Test Accuracy : 84.40

Confusion Matrix:
 [[6250  504]
 [ 908 1387]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.93      0.90      6754
           1       0.73      0.60      0.66      2295

    accuracy                           0.84      9049
   macro avg       0.80      0.76      0.78      9049
weighted avg       0.84      0.84      0.84      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 85.04
Test Accuracy : 84.27

Confusion Matrix:
 [[6287  467]
 [ 956 1339]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.93      0.90      6754
           1       0.74      0.58      0.65      2295

    accuracy                           0.84      9049
   macro avg       0.80      0.76      0.78      9049
weighted avg       0.84      0.84      0.84      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='poly', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 86.49
Test Accuracy : 84.56

Confusion Matrix:
 [[6318  436]
 [ 961 1334]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.94      0.90      6754
           1       0.75      0.58      0.66      2295

    accuracy                           0.85      9049
   macro avg       0.81      0.76      0.78      9049
weighted avg       0.84      0.85      0.84      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 86.35
Test Accuracy : 84.94

Confusion Matrix:
 [[6308  446]
 [ 917 1378]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.93      0.90      6754
           1       0.76      0.60      0.67      2295

    accuracy                           0.85      9049
   macro avg       0.81      0.77      0.79      9049
weighted avg       0.84      0.85      0.84      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='sigmoid', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 78.01
Test Accuracy : 76.69

Confusion Matrix:
 [[5705 1049]
 [1060 1235]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.84      0.84      6754
           1       0.54      0.54      0.54      2295

    accuracy                           0.77      9049
   macro avg       0.69      0.69      0.69      9049
weighted avg       0.77      0.77      0.77      9049

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = gnb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 46.48
Test Accuracy : 46.51

Confusion Matrix:
 [[2027 4727]
 [ 113 2182]]

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.30      0.46      6754
           1       0.32      0.95      0.47      2295

    accuracy                           0.47      9049
   macro avg       0.63      0.63      0.46      9049
weighted avg       0.79      0.47      0.46      9049

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 97.90
Test Accuracy : 84.06

Confusion Matrix:
 [[6175  579]
 [ 863 1432]]

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.91      0.90      6754
           1       0.71      0.62      0.67      2295

    accuracy                           0.84      9049
   macro avg       0.79      0.77      0.78      9049
weighted avg       0.84      0.84      0.84      9049

In [ ]:
from sklearn.utils import resample

length = len(data)

majority_class = data[data['Income'] == 0]
minority_class = data[data['Income'] == 1]

minority_oversampled = resample(
    minority_class,
    replace=True,
    n_samples=length//2,
    random_state=42
)

majority_undersampled = resample(
    majority_class,
    replace=False,
    n_samples=length//2,
    random_state=42
)

majority_unused = majority_class.drop(majority_undersampled.index)

balanced_data = pd.concat([minority_oversampled, majority_undersampled])

balanced_distribution = balanced_data['Income'].value_counts()
balanced_data.shape, balanced_distribution

((30162, 103),
 Income
 1    15081
 0    15081
 Name: count, dtype: int64)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

columns_to_scale = ["Age", "Education Number", "Capital Gain", "Capital Loss", "Hours Per Week"]

scaler = StandardScaler()
balanced_data[columns_to_scale] = scaler.fit_transform(balanced_data[columns_to_scale])

X = balanced_data.drop("Income", axis=1)
y = balanced_data["Income"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()

majority_unused[columns_to_scale] = scaler.fit_transform(majority_unused[columns_to_scale])

X_unused = majority_unused.drop("Income", axis=1)
y_unused = majority_unused["Income"]
X_unused = X_unused.to_numpy()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = knn.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 86.17
Unused Accuracy : 71.27
Test Accuracy : 82.20

Confusion Matrix:
 [[3428 1034]
 [ 577 4010]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.77      0.81      4462
           1       0.80      0.87      0.83      4587

    accuracy                           0.82      9049
   macro avg       0.83      0.82      0.82      9049
weighted avg       0.83      0.82      0.82      9049

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='gini', random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 98.04
Unused Accuracy : 74.20
Test Accuracy : 86.84

Confusion Matrix:
 [[3702  760]
 [ 431 4156]]

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.83      0.86      4462
           1       0.85      0.91      0.87      4587

    accuracy                           0.87      9049
   macro avg       0.87      0.87      0.87      9049
weighted avg       0.87      0.87      0.87      9049

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='entropy', random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 98.04
Unused Accuracy : 74.22
Test Accuracy : 86.74

Confusion Matrix:
 [[3702  760]
 [ 440 4147]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.83      0.86      4462
           1       0.85      0.90      0.87      4587

    accuracy                           0.87      9049
   macro avg       0.87      0.87      0.87      9049
weighted avg       0.87      0.87      0.87      9049

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='log_loss', random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = dt_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 98.04
Unused Accuracy : 74.22
Test Accuracy : 86.74

Confusion Matrix:
 [[3702  760]
 [ 440 4147]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.83      0.86      4462
           1       0.85      0.90      0.87      4587

    accuracy                           0.87      9049
   macro avg       0.87      0.87      0.87      9049
weighted avg       0.87      0.87      0.87      9049

In [ ]:
from sklearn.linear_model import LogisticRegression

log_reg  = LogisticRegression(random_state=42)
log_reg .fit(X_train, y_train)

y_pred = log_reg.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = log_reg.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = log_reg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 82.21
Unused Accuracy : 68.11
Test Accuracy : 82.06

Confusion Matrix:
 [[3540  922]
 [ 701 3886]]

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.79      0.81      4462
           1       0.81      0.85      0.83      4587

    accuracy                           0.82      9049
   macro avg       0.82      0.82      0.82      9049
weighted avg       0.82      0.82      0.82      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 81.01
Unused Accuracy : 73.27
Test Accuracy : 81.06

Confusion Matrix:
 [[3387 1075]
 [ 639 3948]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.76      0.80      4462
           1       0.79      0.86      0.82      4587

    accuracy                           0.81      9049
   macro avg       0.81      0.81      0.81      9049
weighted avg       0.81      0.81      0.81      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='poly', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 84.81
Unused Accuracy : 70.41
Test Accuracy : 83.37

Confusion Matrix:
 [[3499  963]
 [ 542 4045]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.78      0.82      4462
           1       0.81      0.88      0.84      4587

    accuracy                           0.83      9049
   macro avg       0.84      0.83      0.83      9049
weighted avg       0.84      0.83      0.83      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 84.30
Unused Accuracy : 69.38
Test Accuracy : 83.42

Confusion Matrix:
 [[3514  948]
 [ 552 4035]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.79      0.82      4462
           1       0.81      0.88      0.84      4587

    accuracy                           0.83      9049
   macro avg       0.84      0.83      0.83      9049
weighted avg       0.84      0.83      0.83      9049

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(kernel='sigmoid', random_state=42)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 72.66
Unused Accuracy : 64.60
Test Accuracy : 72.78

Confusion Matrix:
 [[3252 1210]
 [1253 3334]]

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.73      0.73      4462
           1       0.73      0.73      0.73      4587

    accuracy                           0.73      9049
   macro avg       0.73      0.73      0.73      9049
weighted avg       0.73      0.73      0.73      9049

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = gnb.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = gnb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 67.74
Unused Accuracy : 40.00
Test Accuracy : 69.04

Confusion Matrix:
 [[1878 2584]
 [ 218 4369]]

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.42      0.57      4462
           1       0.63      0.95      0.76      4587

    accuracy                           0.69      9049
   macro avg       0.76      0.69      0.66      9049
weighted avg       0.76      0.69      0.67      9049

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_train)

accuracy = accuracy_score(y_train, y_pred)
print(f"Train Accuracy : {accuracy*100:.2f}")

y_pred = rf.predict(X_unused)

accuracy = accuracy_score(y_unused, y_pred)
print(f"Unused Accuracy : {accuracy*100:.2f}")

y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy : {accuracy*100:.2f}")

cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Train Accuracy : 98.03
Unused Accuracy : 77.96
Test Accuracy : 88.51

Confusion Matrix:
 [[3764  698]
 [ 342 4245]]

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.84      0.88      4462
           1       0.86      0.93      0.89      4587

    accuracy                           0.89      9049
   macro avg       0.89      0.88      0.88      9049
weighted avg       0.89      0.89      0.88      9049